spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false # jdbc5 版本
#    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=AEST%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: toor

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_ # 全局映射表名
      id-type: auto # 全局id自增
  type-aliases-package: au.com.vincentbai.mybatisplusbasic.pojo